apiVersion: v1
kind: Service
metadata:
  name: review-classifier-service
spec:
  selector:
    app: review-classifier
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
